version: '3.5'
services:
  db:
    image: postgres:12-alpine
    hostname: db
    command: postgres -c 'max_connections=480' -c 'shared_buffers=900MB' -c 'effective_cache_size=900MB'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    network_mode: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
        reservations:
          cpus: '0.4'
          memory: '0.9GB'
  
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
      - api4
      - api5
      - api6
      - api7
      - api8
      - api9
      - api10
    ports:
      - "9999:9999"
    network_mode: host
    extra_hosts:
      - api1:127.0.0.1
      - api2:127.0.0.1
      - api3:127.0.0.1
      - api4:127.0.0.1
      - api5:127.0.0.1
      - api6:127.0.0.1
      - api7:127.0.0.1
      - api8:127.0.0.1
      - api9:127.0.0.1
      - api10:127.0.0.1
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.8GB'
        reservations:
          cpus: '0.1'
          memory: '0.6GB'

  api1: &app
    build:
      context: .
    image: rinha-api
    hostname: api1
    restart: always
    ports:
      - "3401"
    env_file: 
      -  path: .env
    environment:
      PORT: 3401
      SHOW_LOG: false
      CLUSTER_WORKERS: 1
      DATABASE_URL: postgresql://pguser:pgpass@db:5432/pgdb?schema=public&connection_limit=60&pool_timeout=30
    depends_on:
      - db
    network_mode: host
    extra_hosts:
      - db:127.0.0.1
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.09'
          memory: '0.12GB'
        reservations:
          cpus: '0.09'
          memory: '0.1GB'
  
  api2:
    <<: *app
    hostname: api2
    ports:
      - "3402"
    environment:
      PORT: 3402
      SHOW_LOG: false
      CLUSTER_WORKERS: 1
  
  api3:
    <<: *app
    hostname: api3
    ports:
      - "3403"
    environment:
      PORT: 3403
      SHOW_LOG: false
      CLUSTER_WORKERS: 1
  
  api4:
    <<: *app
    hostname: api4
    ports:
      - "3404"
    environment:
      PORT: 3404
      SHOW_LOG: false
      CLUSTER_WORKERS: 1

  api5:
    <<: *app
    hostname: api5
    ports:
      - "3405"
    environment:
      PORT: 3405
      SHOW_LOG: false
      CLUSTER_WORKERS: 1

  api6:
    <<: *app
    hostname: api6
    ports:
      - "3406"
    environment:
      PORT: 3406
      SHOW_LOG: false
      CLUSTER_WORKERS: 1

  api7:
    <<: *app
    hostname: api7
    ports:
      - "3407"
    environment:
      PORT: 3407
      SHOW_LOG: false
      CLUSTER_WORKERS: 1

  api8:
    <<: *app
    hostname: api8
    ports:
      - "3408"
    environment:
      PORT: 3408
      SHOW_LOG: false
      CLUSTER_WORKERS: 1

  api9:
    <<: *app
    hostname: api9
    ports:
      - "3409"
    environment:
      PORT: 3409
      SHOW_LOG: false
      CLUSTER_WORKERS: 1

  api10:
    <<: *app
    hostname: api10
    ports:
      - "3410"
    environment:
      PORT: 3410
      SHOW_LOG: false
      CLUSTER_WORKERS: 1
