version: '3.5'
services:
  db:
    image: postgres:12-alpine
    hostname: db
    command: postgres -c 'max_connections=600' -c 'shared_buffers=900MB' -c 'effective_cache_size=900MB'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    network_mode: host
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
        reservations:
          cpus: '0.45'
          memory: '0.9GB'
  
  nginx:
     image: nginx:1.27-alpine
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./uuid.conf:/etc/nginx/conf.d/uuid.conf:ro
     depends_on:
       - api1
       - api2
     ports:
       - "9999:9999"
     network_mode: host
     extra_hosts:
       - api1:127.0.0.1
       - api2:127.0.0.1
     ulimits:
       nproc: 1000000
       nofile:
         soft: 1000000
         hard: 1000000
     deploy:
       resources:
         limits:
           cpus: '0.4'
           memory: '0.5GB'
         reservations:
           cpus: '0.35'
           memory: '0.45GB'

  api1: &app
    build:
      context: .
    image: rinha-kotlin-api
    platform: linux/x86_64
    hostname: api1
    restart: always
    ports:
      - "3401"
    environment:
      PORT: 3401
      DB_URL: "jdbc:postgresql://localhost:5432/pgdb"
      PG_PASSWORD: "pgpass"
      PG_USER: "pguser"
      POOLSIZE: 200
    depends_on:
      - db
    network_mode: host
    extra_hosts:
      - db:127.0.0.1
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    command:
      - "java"
      - "-XX:+UseParallelGC"
      - "-XX:ParallelGCThreads=2"
      - "-Xms570m"
      - "-Xmx570m"
      - "-jar"
      - "./build/libs/backend-0.0.1-SNAPSHOT.jar"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.75GB'
        reservations:
          cpus: '0.25'
          memory: '0.65GB'

  api2:
    <<: *app
    hostname: api2
    ports:
      - "3402"
    environment:
      PORT: 3402
      DB_URL: "jdbc:postgresql://localhost:5432/pgdb"
      PG_PASSWORD: "pgpass"
      PG_USER: "pguser"
      POOLSIZE: 200
  
  # api3:
  #   <<: *app
  #   hostname: api3
  #   ports:
  #     - "3403"
  #   environment:
  #     PORT: 3403
  #     SHOW_LOG: false
  
